name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@372546727d8ab7f408d3db6583dcc103be8b7f59
        with: 
            owner: NamrataJha
            repo: only-pkg
            package-name: only-pkg
            num-old-versions-to-delete: 10

 


          
