name: delete-old-packages
  # You may pin to the exact commit or the version.
  # uses: SmartsquareGmbH/delete-old-packages@87726d22de419a4d3c467bb118ebc17c010b806f
on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package 1
        uses: actions/delete-package-versions@v2
        with: 
            owner: NamrataJha
            repo: only-pkg
            package-name: sample-npm-1
            num-old-versions-to-delete: 1
      - name: Delete package 2
        uses: actions/delete-package-versions@v2
        with: 
            owner: NamrataJha
            repo: only-pkg
            package-name: sample-npm-2
            num-old-versions-to-delete: 1
