name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        node: ['only-pkg','only-pkg','only-pkg','only-pkg','only-pkg','only-pkg','only-pkg','only-pkg','only-pkg','only-pkg']
      
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@8283350471d9e648bf28ae366f80671aa50d528e
        with: 
            owner: NamrataJha
            repo: only-pkg
            package-name: ${{ matrix.node }}
            min-versions-to-keep: 50
      

 


          
