name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@e9faf3233c9ef3187565121e358fbe57793d0c45
        with: 
            owner: NamrataJha
            repo: only-pkg
            package-name: only-pkg
            num-old-versions-to-delete: 10

 


          
