name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete package
        uses: actions/delete-package-versions@e6a9d9c8022cd2b0277022e30d6f3a28cef8e1e1
        with: 
            owner: NamrataJha
            repo: only-pkg
            package-name: only-pkg
            min-versions-to-keep: 20

 


          
